---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Template For SNS Topic'
Parameters:
  OperatorEmail:
    Description: Email address to notify if there are any operational issues
    Type: String
    Default: @gmail.com
    AllowedPattern: "([a-zA-Z0-9_\\-\\.]+)@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\\]?)"
    ConstraintDescription: must be a valid email address.
Resources:
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint:
          Ref: OperatorEmail
        Protocol: email
Outputs:
  SNSTopicArn:
    Description: SNS Arn details
    Value: !GetAttr NotificationTopic.Arn
  
